### ISSUE TITLE
Can we add accessibility tests with eslint-plugin-js-a11y?

### ISSUE THREAD

**Issue by S-unya** [aerian-studios/eslint-config#1]

**Comment by S-unya** [comment]
The reason I opened an issue is to start the conversation; I'm not entirely sure how widely appropriate it is.

There are other tools that can be built in to the toolchain, e.g. the react specific, https://github.com/dequelabs/react-axe, or even using axe directly

**Comment by ascorbic** [comment]
We already do! They're in the React config though, as they're jsx-specific.

**Comment by S-unya** [comment]
hah! of course we do! :D
